information = lambda name, sername, year, sity, email, number: print(name, ' ',sername, ' ', year, ' ', sity, ' ', email, ' ', number)
print('введите ваше имя')
name = input()
print('введите вашу фамилию')
sername = input()
print('введите год вашего рождения')
year = input()
print('введите город вашего проживания')
sity = input
print('введите вашу почту')
email = input()
print('введите ваш номер телефона')
number = input()
print('результат действия функции')
information(name, sername, year, sity, email, number)