func = lambda num_1, num_2, num_3: num_1 + num_2 + num_3 - min(num_1, num_2, num_3)
num_1 = int(input())
num_2 = int(input())
num_3 = int(input())
print('сумма наибольших аргументов = ', func(num_1, num_2, num_3))